### PR TITLE
Add support for Linux

### PR DESCRIPTION
**Pull request by mgrojo**
See [issue #1 in qt5ada](https://github.com/ohenley/qt5ada/issues/1).

### CODE REVIEW

**Comment by mgrojo** [comment]
Unfortunately, the GitHub Action is not working because it refuses to download [qt5.15x86-64.tar.bz2](https://r3fowwcolhrzycn2yzlzzw-on.drv.tw/AdaStudio/qtada/qt5.15x86-64.tar.bz2), probably due to security concerns or due to the redirection that Google Drive is performing. Maybe that can be solved making a release in your Qt5Ada repository and uploading that archive as asset, so it can be downloaded from GitHub itself. Assuming that GitHub will allow that.

In any case, as I already commented, this is not the best way to provide Qt5Ada. There is no source code for libqt5c and the result is too coupled to a particular Qt version, instead of letting the user link only against the Qt modules that they use.

**Comment by mgrojo** [comment]
I finally made the trick of downloading from a GitHub release instead of the upstream version. In order to make it work using your qt5ada repository you'll have to make a release in your repository, upload the archives and change the URLs in the Makefile to point to your release.

The Continuous Integration Action is working now, which is nice to check that every push works under Ubuntu Linux.

**Comment by mgrojo** [comment]
The same approach could be used for the Windows binaries, instead of including them in the repository. The problem is how to do it in Windows without wget and make.

**Comment by mgrojo** [comment]
Forgive all the trial commits, some times I thought I was committing to a secondary branch instead of master. That will be better squashed and merged using the GitHub control button.

Unfortunately, the generated and released AppImage through the GitHub Action is not working in my system and I don't know how to solve it. Maybe it's better to disable releasing it, if it cannot be solved.

**Comment by ohenley** [comment]
Wow man, you make my month. Your contribution is beyond great! :)

I just learned a few things (actions, appimage, some gpr capabilities) by looking at your PR. 
Thx for pushing to have a solution for Qt5Ada as a Github repo (Linux)
Finally, thx for having company to improve, in my opinion, this great little collaborative project of a simulator. 

I will merge with pleasure. Also do not hesitate to 'push' this project forward. I think it serves a great 'demo' for Ada and is quite interesting scientifically speaking.  Things which were on my TODO scope, just to let you know the main glitches:

- Progress bar with task abort, updated information etc 
- Re-architecture to decouple the 'simulation engine'. A first approximation, more or less sufficient, exists for the 'xph engine' but as you can see the 'lancet engine' lives anywhere and everywhere.
- Window resize (facepalm). At one point I contemplated a move to QML to inherit some 'flexbox' like capabilities. I put this one on ice because I lack the Qt knowledge depth to make this happen quickly.  
- The export to .csv, I ninja-ed its refactor a bit and it might be broken but not much. Ada refactors that compile are quite robust in my opinion.

While I am there, I will open issues/features for these...

Anyway, anything welcome, I like to share thoughts, discussions, super happy to meet you and thx again.

**Comment by mgrojo** [comment]
Yeah, your application is very interesting as a showcase for Ada and Qt5Ada. I'd be glad to collaborate- Maybe I can take advantage of the knowledge about Qt that I've gathered in sqlitebrowser.

**Comment by ohenley** [comment]
Seriously! What a coincidence, I used sqlitebrowser a lot 2 years ago. I found its the best/intuitive/complete browser for SQLite. It saved my day on many occasions and I swear by it anytime SQLite comes up.

I do some C++ and Python Qt at my day job but never got extensive training/use of it. Among many things, I make UI/UX of plugins, always in a somewhat sandboxed context. Sometimes I lack the 'tricks of the trade' for advanced behaviors. I would be glad to learn how you do things on more substantial scopes. No pressure though. :)

**Pull request merged**
