### PR TITLE
Bundle Qt and dependencies inside AppImage correctly

### PR DESCRIPTION
**Pull request by mgrojo**
Use Ubuntu Xenial Qt-5.15 repository and linuxdeploy-plugin-qt for the
action that builds the AppImage.

See issue #12

### CODE REVIEW

**Comment by mgrojo** [comment]
Sorry about all the trials. I cannot test locally.

**Comment by ohenley** [comment]
No worries.

**Comment by mgrojo** [comment]
This is ready for review and eventual merge. I've squashed the branch to remove the trial commits.

**Comment by ohenley** [comment]
Thx @mgrojo for taking care of that.

**Pull request merged**
